In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

1.13.1+cu117


In [2]:
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# tensor back as python int
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8],[1,3]])
MATRIX

tensor([[7, 8],
        [1, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([1, 3])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1,2,3],[5,6,4],[7,8,9],[4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 4],
         [7, 8, 9],
         [4, 5, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 4, 3])

### Random Tensors

Random tensors are imp bc the way many nn learn is that they start with tensors full of random numbers and then adjust those random numbers
to better represent data


In [17]:
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.9328, 0.6516, 0.0790, 0.4870],
         [0.4196, 0.9089, 0.3953, 0.0245],
         [0.1478, 0.9368, 0.0494, 0.4796]]])

In [18]:
random_tensor.ndim

3

In [19]:
random_image_size = torch.rand(size =(256,256,3))
random_image_size

tensor([[[6.3531e-01, 9.6447e-01, 7.8929e-01],
         [5.6998e-01, 8.3630e-01, 1.6826e-01],
         [6.7721e-01, 3.7317e-01, 2.8860e-02],
         ...,
         [7.3397e-01, 6.4298e-01, 2.2605e-01],
         [1.4127e-01, 1.8702e-01, 3.2289e-01],
         [7.7338e-01, 7.7315e-01, 9.9750e-01]],

        [[2.4099e-01, 9.3657e-01, 6.4907e-01],
         [1.9554e-01, 2.6872e-01, 1.7125e-01],
         [8.5153e-02, 8.8727e-01, 2.8387e-03],
         ...,
         [1.8417e-01, 3.5825e-01, 5.7248e-01],
         [9.5099e-01, 9.1069e-01, 6.7080e-01],
         [9.1257e-01, 1.4581e-01, 4.3530e-01]],

        [[5.2887e-04, 2.7335e-02, 2.8358e-01],
         [6.3915e-01, 7.7547e-01, 6.5777e-01],
         [6.1604e-01, 2.6190e-02, 2.0766e-01],
         ...,
         [1.0736e-02, 9.0165e-01, 8.3196e-01],
         [1.8138e-01, 3.7787e-01, 8.2920e-02],
         [2.2337e-01, 8.4649e-01, 5.6449e-01]],

        ...,

        [[9.4694e-01, 1.4517e-01, 3.1469e-01],
         [6.0902e-01, 3.5449e-01, 6.1096e-01]

In [20]:
random_image_size.size()

torch.Size([256, 256, 3])

In [21]:
random_image_size.shape

torch.Size([256, 256, 3])

In [22]:
zeroes = torch.zeros(size=(1,3,4))
zeroes

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
zeroes*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
one_to_ten  = torch.arange(0,10)

In [25]:
torch.arange(start =1 ,end = 10,step = 3)

tensor([1, 4, 7])

In [26]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
## Tensor dtypes

float_32_tensor = torch.tensor([3.,6.0,9.0],dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32 = torch.tensor([3.,6.0,9.0],dtype = torch.float16)
float_32

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_32 = torch.tensor([3.,6.0,9.0],dtype = None,device = None,requires_grad = False)
float_32

tensor([3., 6., 9.])

In [30]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32 = torch.tensor([3,6,9],dtype = torch.int32)
int_32

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_16*int_32

tensor([ 9., 36., 81.], dtype=torch.float16)

In [34]:
tensor = torch.rand(4,4)
tensor

tensor([[0.6408, 0.2330, 0.8292, 0.2922],
        [0.3464, 0.0705, 0.5576, 0.4762],
        [0.1901, 0.4561, 0.7315, 0.9219],
        [0.5916, 0.2953, 0.8143, 0.6994]])

In [35]:
# attributes of tensors

print(tensor)
print(f'dtype of tensor:{tensor.dtype}')
print(f'shape of tensor:{tensor.shape}')
print(f'device of tensor:{tensor.device}')

tensor([[0.6408, 0.2330, 0.8292, 0.2922],
        [0.3464, 0.0705, 0.5576, 0.4762],
        [0.1901, 0.4561, 0.7315, 0.9219],
        [0.5916, 0.2953, 0.8143, 0.6994]])
dtype of tensor:torch.float32
shape of tensor:torch.Size([4, 4])
device of tensor:cpu


In [36]:
int_32_tensor = torch.tensor([3,6,9],dtype =torch.int32,device = 'cuda',requires_grad = False)
int_32_tensor

tensor([3, 6, 9], device='cuda:0', dtype=torch.int32)

In [37]:
# arithmetic operations on tensors

tensor =  torch.tensor([1,2,3])
tensor + 20

tensor([21, 22, 23])

In [38]:
tensor * 20

tensor([20, 40, 60])

In [39]:
tensor / 20

tensor([0.0500, 0.1000, 0.1500])

In [40]:
tensor // 20

tensor([0, 0, 0])

In [41]:
tensor % 20

tensor([1, 2, 3])

In [42]:
tensor - 5

tensor([-4, -3, -2])

In [43]:
# PyTorch inbuild functions

torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [45]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [46]:
torch.div(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

In [47]:
# matrix multiplication or dot product

tensor_a =  torch.rand(5,3)
tensor_b = torch.rand(3,5)

In [48]:
%%time
torch.matmul(tensor_a,tensor_b)

CPU times: total: 0 ns
Wall time: 999 µs


tensor([[0.7348, 0.8475, 0.2904, 0.3927, 1.4951],
        [0.7595, 0.6737, 0.2919, 0.3264, 1.1517],
        [0.6737, 0.5763, 0.9181, 0.8023, 1.2290],
        [0.3883, 0.5617, 0.3998, 0.4431, 1.1027],
        [0.7724, 0.7181, 0.3007, 0.3468, 1.2363]])

In [49]:
tensor_c =  torch.rand(3,3)
tensor_d = torch.rand(3,3)
torch.matmul(tensor_c,tensor_d)

tensor([[0.8867, 1.1296, 0.4165],
        [0.5661, 0.6291, 0.0428],
        [0.7890, 1.1472, 0.2771]])

In [50]:
tensor_c @ tensor_b

tensor([[0.5638, 0.4341, 0.8086, 0.6858, 0.9506],
        [0.7337, 0.5603, 0.0399, 0.0915, 0.8467],
        [0.8957, 0.7850, 0.2509, 0.3078, 1.3048]])

In [51]:
tensor_e = torch.rand(3,4)
tensor_e

tensor([[0.5926, 0.2227, 0.4298, 0.0105],
        [0.5288, 0.7440, 0.0307, 0.7249],
        [0.1929, 0.3340, 0.9569, 0.8687]])

In [52]:
torch.mm(tensor_a,tensor_e)

tensor([[0.9035, 0.7691, 0.5729, 0.6832],
        [0.6588, 0.7475, 0.4140, 0.8052],
        [0.6132, 0.6887, 1.0824, 1.1068],
        [0.6535, 0.4443, 0.6717, 0.4452],
        [0.7150, 0.7680, 0.4528, 0.8042]])

In [53]:
# Transpose matrix

tensor_a.T

tensor([[0.8421, 0.3206, 0.3819, 0.8114, 0.4161],
        [0.6926, 0.7905, 0.3861, 0.2058, 0.7906],
        [0.1983, 0.2634, 0.9472, 0.3309, 0.2610]])

In [54]:
tensor_e.T

tensor([[0.5926, 0.5288, 0.1929],
        [0.2227, 0.7440, 0.3340],
        [0.4298, 0.0307, 0.9569],
        [0.0105, 0.7249, 0.8687]])

In [55]:
# find min,max,sum,mean

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
torch.min(x)

tensor(0)

In [57]:
x.min()

tensor(0)

In [58]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [59]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [60]:
x.type(torch.float32).mean()

tensor(45.)

In [61]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [62]:
# to find the min and max position in the tensor

x.argmin(),x.argmax()

(tensor(0), tensor(9))

In [63]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
# Reshape,stacking,squeezing,unsqueezing

tensor_x = torch.arange(1.,10.)
tensor_x,tensor_x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
reshape_tensor_x = tensor_x.reshape(1,9)
reshape_tensor_x,reshape_tensor_x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
y = tensor_x.view(1,9)
y,y.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
stack_tensor_x = torch.stack([tensor_x,tensor_x,tensor_x],dim = 1)
stack_tensor_x

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [68]:
torch.squeeze(tensor_x)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
tensor_x.shape

torch.Size([9])

In [70]:
tensor_x.unsqueeze(dim = 0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [71]:
tensor_x.shape

torch.Size([9])

In [72]:
tensor_x_unsqueeze  = torch.unsqueeze(tensor_x,dim = 0)
tensor_x_unsqueeze

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [73]:
tensor_x_unsqueeze.shape

torch.Size([1, 9])

In [74]:
x = torch.rand(size=(256,256,3))
x.size()

torch.Size([256, 256, 3])

In [75]:
x_permuted = x.permute(2,0,1)
x_permuted.size()

torch.Size([3, 256, 256])

In [76]:
x[0,0,0] = 123
x[0,0,0],x_permuted[0,0,0]

(tensor(123.), tensor(123.))

In [77]:
a = torch.arange(1,10).reshape(1,3,3)
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [78]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
a[0][0]

tensor([1, 2, 3])

In [80]:
a[0][0][0]

tensor(1)

In [81]:
a[0][1][0]

tensor(4)

In [82]:
a[0][2][2]

tensor(9)

In [83]:
a[:,0]

tensor([[1, 2, 3]])

In [84]:
a[:,:,0]

tensor([[1, 4, 7]])

In [85]:
a[:,1,1]

tensor([5])

In [86]:
a[0,0,:]

tensor([1, 2, 3])

In [87]:
a[:,:,2]

tensor([[3, 6, 9]])

In [88]:
# numpy array to tensor
arr = np.arange(1.0,8.0)
tensor_arr = torch.from_numpy(arr)
arr, tensor_arr

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
arr.dtype

dtype('float64')

In [90]:
tensor_arr = torch.from_numpy(arr).type(torch.float32)
arr, tensor_arr

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [91]:
arr.dtype,tensor_arr.dtype

(dtype('float64'), torch.float32)

In [92]:
arr = arr +1
arr,tensor_arr

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [93]:
tensor_ones = torch.ones(7)
numpy_tensor = tensor_ones.numpy()
tensor_ones,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [94]:
tensor_ones = tensor_ones + 1
tensor_ones,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
# reproducibility trying to take random out of random
# to reduce randomness we use random seed
tensor_rand_A = torch.rand(4,4)
tensor_rand_B = torch.rand(4,4)

In [96]:
print(tensor_rand_A)
print(tensor_rand_B)

tensor([[0.5952, 0.2868, 0.8954, 0.2868],
        [0.6400, 0.8821, 0.0222, 0.6666],
        [0.6832, 0.7316, 0.8797, 0.5965],
        [0.8055, 0.4248, 0.4034, 0.9892]])
tensor([[0.8388, 0.0770, 0.7794, 0.4373],
        [0.2269, 0.5963, 0.3213, 0.9792],
        [0.6427, 0.1891, 0.7947, 0.1180],
        [0.1834, 0.7947, 0.9931, 0.9019]])


In [97]:
tensor_rand_A == tensor_rand_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [98]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_rand_C = torch.rand(4,4)

torch.manual_seed(RANDOM_SEED)
tensor_rand_D = torch.rand(4,4)

print(tensor_rand_C)
print(tensor_rand_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])


In [99]:
tensor_rand_C == tensor_rand_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [100]:
!nvidia-smi

Sat Jan 14 20:03:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.02       Driver Version: 528.02       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   48C    P0    26W /  82W |    546MiB /  6144MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [101]:
# checking GPU access with PyTorch

torch.cuda.is_available()

True

In [102]:
torch.cuda.device_count()

1

In [103]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [104]:
tesor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [105]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [106]:
# if tensor is on gpu ,can't transform it to numpy

tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3], dtype=int64)